package PreparingTeamsAndPlayers

//making Japan Players
import "github.com/DenisKDO/Vollyball-API/pkg/essences"

func JapanPlayers() []essences.Player {
	var players []essences.Player

	var player essences.Player

	//Japan volleyball national team
	player.UniformNumber = 1
	player.Position = "OP"
	player.FirstName = "Yuji"
	player.SecondName = "Nishida"
	player.Height = 186
	player.Weight = 80
	player.SpikeHeight = 350
	player.BlockHeight = 335
	player.DateOfBirth = "January 30, 2000"
	player.Age = 24
	player.TeamTitle = "Japan men's national volleyball team"
	player.TeamID = 1
	players = append(players, player)

	player.UniformNumber = 12
	player.Position = "OH"
	player.FirstName = "Ran"
	player.SecondName = "Takahashi"
	player.Height = 188
	player.Weight = 72
	player.SpikeHeight = 343
	player.BlockHeight = 315
	player.DateOfBirth = "September 2, 2001"
	player.Age = 22
	player.TeamTitle = "Japan men's national volleyball team"
	player.TeamID = 1
	players = append(players, player)

	player.UniformNumber = 15
	player.Position = "OH"
	player.FirstName = "Masahiro"
	player.SecondName = "Yanagida"
	player.Height = 186
	player.Weight = 80
	player.SpikeHeight = 335
	player.BlockHeight = 305
	player.DateOfBirth = "July 6, 1992"
	player.Age = 31
	player.TeamTitle = "Japan men's national volleyball team"
	player.TeamID = 1
	players = append(players, player)

	player.UniformNumber = 18
	player.Position = "OP"
	player.FirstName = "Hiroto"
	player.SecondName = "Nishiyama"
	player.Height = 193
	player.Weight = 77
	player.SpikeHeight = 355
	player.BlockHeight = 330
	player.DateOfBirth = "March 4, 2003"
	player.Age = 20
	player.TeamTitle = "Japan men's national volleyball team"
	player.TeamID = 1
	players = append(players, player)

	player.UniformNumber = 19
	player.Position = "L"
	player.FirstName = "Satoshi"
	player.SecondName = "Tsuiki"
	player.Height = 174
	player.Weight = 74
	player.SpikeHeight = -1
	player.BlockHeight = -1
	player.DateOfBirth = "January 16, 1992"
	player.Age = 32
	player.TeamTitle = "Japan men's national volleyball team"
	player.TeamID = 1
	players = append(players, player)

	player.UniformNumber = 14
	player.Position = "OH"
	player.FirstName = "Yuki"
	player.SecondName = "Ishikawa"
	player.Height = 191
	player.Weight = 84
	player.SpikeHeight = 351
	player.BlockHeight = 327
	player.DateOfBirth = "December 11, 1995"
	player.Age = 28
	player.TeamTitle = "Japan men's national volleyball team"
	player.TeamID = 1
	players = append(players, player)

	player.UniformNumber = 4
	player.Position = "OP"
	player.FirstName = "Kento"
	player.SecondName = "Miyaura"
	player.Height = 189
	player.Weight = 78
	player.SpikeHeight = 347
	player.BlockHeight = 320
	player.DateOfBirth = "February 22, 1999"
	player.Age = 24
	player.TeamTitle = "Japan men's national volleyball team"
	player.TeamID = 1
	players = append(players, player)

	player.UniformNumber = 5
	player.Position = "OH"
	player.FirstName = "Tatsunori"
	player.SecondName = "Otsuka"
	player.Height = 194
	player.Weight = 80
	player.SpikeHeight = 340
	player.BlockHeight = 325
	player.DateOfBirth = "November 5, 2000"
	player.Age = 23
	player.TeamTitle = "Japan men's national volleyball team"
	player.TeamID = 1
	players = append(players, player)

	player.UniformNumber = 23
	player.Position = "MB"
	player.FirstName = "Shunichiro"
	player.SecondName = "Sato"
	player.Height = 204
	player.Weight = 94
	player.SpikeHeight = 340
	player.BlockHeight = 323
	player.DateOfBirth = "May 17, 2000"
	player.Age = 23
	player.TeamTitle = "Japan men's national volleyball team"
	player.TeamID = 1
	players = append(players, player)

	player.UniformNumber = 24
	player.Position = "L"
	player.FirstName = "Kazuyuki"
	player.SecondName = "Takahashi"
	player.Height = 170
	player.Weight = 62
	player.SpikeHeight = 310
	player.BlockHeight = -1
	player.DateOfBirth = "January 26, 2000"
	player.Age = 24
	player.TeamTitle = "Japan men's national volleyball team"
	player.TeamID = 1
	players = append(players, player)

	player.UniformNumber = 25
	player.Position = "MB"
	player.FirstName = "Takahiro"
	player.SecondName = "Namba"
	player.Height = 198
	player.Weight = -1
	player.SpikeHeight = -1
	player.BlockHeight = -1
	player.DateOfBirth = "May 1, 1998"
	player.Age = 25
	player.TeamTitle = "Japan men's national volleyball team"
	player.TeamID = 1
	players = append(players, player)

	player.UniformNumber = 16
	player.Position = "MB"
	player.FirstName = "Go"
	player.SecondName = "Murayama"
	player.Height = 192
	player.Weight = 82
	player.SpikeHeight = 341
	player.BlockHeight = 317
	player.DateOfBirth = "July 30, 1998"
	player.Age = 25
	player.TeamTitle = "Japan men's national volleyball team"
	player.TeamID = 1
	players = append(players, player)

	player.UniformNumber = 26
	player.Position = "OH"
	player.FirstName = "Akito"
	player.SecondName = "Yamazaki"
	player.Height = 190
	player.Weight = 75
	player.SpikeHeight = 345
	player.BlockHeight = -1
	player.DateOfBirth = "October 16, 1997"
	player.Age = 26
	player.TeamTitle = "Japan men's national volleyball team"
	player.TeamID = 1
	players = append(players, player)

	//	player.Id = "14"
	//	player.UniformNumber = "27"
	//	player.Country = "Japan"
	//	player.Position = "L"
	//	player.FirstName = "Soshi"
	//	player.SecondName = "Fujinaka"
	//	player.Height = "184cm"
	//	player.Weight = "UNKNOWN"
	//	player.Spike = "UNKNOWN"
	//	player.Block = "UNKNOWN"
	//	player.CurrentClub = "Suntory Sunbirds (Japan)"
	//	player.DateOfBirth = "December 2, 1999 (age 24)"
	//	players = append(players, player)
	//
	//	player.Id = "15"
	//	player.UniformNumber = "28"
	//	player.Country = "Japan"
	//	player.Position = "MB"
	//	player.FirstName = "Larry"
	//	player.SecondName = "Evbade-Dan"
	//	player.Height = "195cm"
	//	player.Weight = "81kg"
	//	player.Spike = "350cm"
	//	player.Block = "333cm"
	//	player.CurrentClub = "Panasonic Panthers (Japan)"
	//	player.DateOfBirth = "December 2, 1999 (age 24)"
	//	players = append(players, player)
	//
	//	player.Id = "16"
	//	player.UniformNumber = "31"
	//	player.Country = "Japan"
	//	player.Position = "OP"
	//	player.FirstName = "Keihan"
	//	player.SecondName = "Takahashi"
	//	player.Height = "193cm"
	//	player.Weight = "78kg"
	//	player.Spike = "350cm"
	//	player.Block = "325cm"
	//	player.CurrentClub = "JTEKT Stings (Japan)"
	//	player.DateOfBirth = "October 13, 2003 (age 20)"
	//	players = append(players, player)
	//
	//	player.Id = "17"
	//	player.UniformNumber = "32"
	//	player.Country = "Japan"
	//	player.Position = "MB"
	//	player.FirstName = "Kento"
	//	player.SecondName = "Asano"
	//	player.Height = "206cm"
	//	player.Weight = "93kg"
	//	player.Spike = "352cm"
	//	player.Block = "UNKNOWN"
	//	player.CurrentClub = "Waseda University (Japan)"
	//	player.DateOfBirth = "December 24, 2004 (age 19)"
	//	players = append(players, player)
	//
	//	player.Id = "18"
	//	player.UniformNumber = "33"
	//	player.Country = "Japan"
	//	player.Position = "L"
	//	player.FirstName = "Kazuma"
	//	player.SecondName = "Sonae"
	//	player.Height = "UNKNOWN"
	//	player.Weight = "UNKNOWN"
	//	player.Spike = "UNKNOWN"
	//	player.Block = "UNKNOWN"
	//	player.CurrentClub = "VC Nagano Tridents (Japan)"
	//	player.DateOfBirth = "January 6, 1998 (age 26)"
	//	players = append(players, player)
	//
	//	player.Id = "19"
	//	player.UniformNumber = "34"
	//	player.Country = "Japan"
	//	player.Position = "OH"
	//	player.FirstName = "Yudai"
	//	player.SecondName = "Arai"
	//	player.Height = "188cm"
	//	player.Weight = "85kg"
	//	player.Spike = "350cm"
	//	player.Block = "UNKNOWN"
	//	player.CurrentClub = "JT Thunders (Japan)"
	//	player.DateOfBirth = "June 27, 1998 (age 25)"
	//	players = append(players, player)
	//
	//	player.Id = "20"
	//	player.UniformNumber = "35"
	//	player.Country = "Japan"
	//	player.Position = "MB"
	//	player.FirstName = "Hirohito"
	//	player.SecondName = "Kashimura"
	//	player.Height = "196cm"
	//	player.Weight = "84kg"
	//	player.Spike = "345cm"
	//	player.Block = "325cm"
	//	player.CurrentClub = "Suntory Sunbirds (Japan)"
	//	player.DateOfBirth = "January 15, 1999 (age 25)"
	//	players = append(players, player)
	//
	//	player.Id = "21"
	//	player.UniformNumber = "36"
	//	player.Country = "Japan"
	//	player.Position = "MB"
	//	player.FirstName = "Hiromasa"
	//	player.SecondName = "Miwa"
	//	player.Height = "192cm"
	//	player.Weight = "UNKNOWN"
	//	player.Spike = "UNKNOWN"
	//	player.Block = "UNKNOWN"
	//	player.CurrentClub = "JT Thunders (Japan)"
	//	player.DateOfBirth = "December 17, 1999 (age 24)"
	//	players = append(players, player)
	//
	//	player.Id = "22"
	//	player.UniformNumber = "37"
	//	player.Country = "Japan"
	//	player.Position = "S"
	//	player.FirstName = "Ryo"
	//	player.SecondName = "Shimokawa"
	//	player.Height = "UNKNOWN"
	//	player.Weight = "UNKNOWN"
	//	player.Spike = "UNKNOWN"
	//	player.Block = "UNKNOWN"
	//	player.CurrentClub = "VC Nagano Tridents (Japan)"
	//	player.DateOfBirth = "January 12, 2000 (age 24)"
	//	players = append(players, player)
	//
	//	player.Id = "23"
	//	player.UniformNumber = "17"
	//	player.Country = "Japan"
	//	player.Position = "OH"
	//	player.FirstName = "Hiroki"
	//	player.SecondName = "Ozawa"
	//	player.Height = "186cm"
	//	player.Weight = "UNKNOWN"
	//	player.Spike = "UNKNOWN"
	//	player.Block = "UNKNOWN"
	//	player.CurrentClub = "Toray Arrows (Japan)"
	//	player.DateOfBirth = "September 21, 1997 (age 26)"
	//	players = append(players, player)
	//
	//	player.Id = "24"
	//	player.UniformNumber = "11"
	//	player.Country = "Japan"
	//	player.Position = "OH"
	//	player.FirstName = "Shoma"
	//	player.SecondName = "Tomita"
	//	player.Height = "190cm"
	//	player.Weight = "75kg"
	//	player.Spike = "342cm"
	//	player.Block = "320cm"
	//	player.CurrentClub = "Toray Arrows (Japan)"
	//	player.DateOfBirth = "June 20, 1997 (age 26)"
	//	players = append(players, player)
	//
	//	player.Id = "25"
	//	player.UniformNumber = "30"
	//	player.Country = "Japan"
	//	player.Position = "OH"
	//	player.FirstName = "Masato"
	//	player.SecondName = "Kai"
	//	player.Height = "184cm"
	//	player.Weight = "72kg"
	//	player.Spike = "352cm"
	//	player.Block = "330cm"
	//	player.CurrentClub = "Paris Volley (France)"
	//	player.DateOfBirth = "September 25, 2003 (age 20)"
	//	players = append(players, player)
	//
	//	player.Id = "26"
	//	player.UniformNumber = "2"
	//	player.Country = "Japan"
	//	player.Position = "MB"
	//	player.FirstName = "Onodera"
	//	player.SecondName = "Taishi"
	//	player.Height = "201cm"
	//	player.Weight = "98kg"
	//	player.Spike = "343cm"
	//	player.Block = "330cm"
	//	player.CurrentClub = "Suntory Sunbirds (Japan)"
	//	player.DateOfBirth = "February 27, 1996 (age 27)"
	//	players = append(players, player)
	//
	//	player.Id = "27"
	//	player.UniformNumber = "6"
	//	player.Country = "Japan"
	//	player.Position = "MB"
	//	player.FirstName = "Akihiro"
	//	player.SecondName = "Yamauchi"
	//	player.Height = "204cm"
	//	player.Weight = "80kg"
	//	player.Spike = "354cm"
	//	player.Block = "335cm"
	//	player.CurrentClub = "Panasonic Panthers (Japan)"
	//	player.DateOfBirth = "November 30, 1993 (age 30)"
	//	players = append(players, player)
	//
	//	player.Id = "28"
	//	player.UniformNumber = "7"
	//	player.Country = "Japan"
	//	player.Position = "MB"
	//	player.FirstName = "Kenta"
	//	player.SecondName = "Takanashi"
	//	player.Height = "190cm"
	//	player.Weight = "83kg"
	//	player.Spike = "347cm"
	//	player.Block = "330cm"
	//	player.CurrentClub = "Wolfdogs Nagoya (Japan)"
	//	player.DateOfBirth = "March 25, 1997 (age 26)"
	//	players = append(players, player)
	//
	//	player.Id = "29"
	//	player.UniformNumber = "10"
	//	player.Country = "Japan"
	//	player.Position = "MB"
	//	player.FirstName = "Kentaro"
	//	player.SecondName = "Takahashi"
	//	player.Height = "201cm"
	//	player.Weight = "103kg"
	//	player.Spike = "361cm"
	//	player.Block = "350cm"
	//	player.CurrentClub = "Toray Arrows (Japan)"
	//	player.DateOfBirth = "February 8, 1995 (age 28)"
	//	players = append(players, player)
	//
	//	player.Id = "30"
	//	player.UniformNumber = "12"
	//	player.Country = "Japan"
	//	player.Position = "S"
	//	player.FirstName = "Masahiro"
	//	player.SecondName = "Sekita"
	//	player.Height = "175cm"
	//	player.Weight = "72kg"
	//	player.Spike = "324cm"
	//	player.Block = "305cm"
	//	player.CurrentClub = "JTEKT Stings (Japan)"
	//	player.DateOfBirth = "November 20, 1993 (age 30)"
	//	players = append(players, player)
	//
	//	player.Id = "31"
	//	player.UniformNumber = "29"
	//	player.Country = "Japan"
	//	player.Position = "S"
	//	player.FirstName = "Ryu"
	//	player.SecondName = "Yamamoto"
	//	player.Height = "180cm"
	//	player.Weight = "65kg"
	//	player.Spike = "330cm"
	//	player.Block = "315cm"
	//	player.CurrentClub = "CS Dinamo București (Romania)"
	//	player.DateOfBirth = "September 23, 2000 (age 23)"
	//	players = append(players, player)
	//
	//	player.Id = "32"
	//	player.UniformNumber = "3"
	//	player.Country = "Japan"
	//	player.Position = "S"
	//	player.FirstName = "Akihiro"
	//	player.SecondName = "Fukatsu"
	//	player.Height = "183cm"
	//	player.Weight = "78kg"
	//	player.Spike = "334cm"
	//	player.Block = "315cm"
	//	player.CurrentClub = "Tokyo Great Bears (Japan)"
	//	player.DateOfBirth = "July 23, 1987 (age 36)"
	//	players = append(players, player)
	//
	//	player.Id = "33"
	//	player.UniformNumber = "9"
	//	player.Country = "Japan"
	//	player.Position = "S"
	//	player.FirstName = "Masaki"
	//	player.SecondName = "Oya"
	//	player.Height = "178cm"
	//	player.Weight = "77kg"
	//	player.Spike = "330cm"
	//	player.Block = "315cm"
	//	player.CurrentClub = "Suntory Sunbirds (Japan)"
	//	player.DateOfBirth = "March 23, 1995 (age 28)"
	//	players = append(players, player)
	//
	//	player.Id = "34"
	//	player.UniformNumber = "13"
	//	player.Country = "Japan"
	//	player.Position = "L"
	//	player.FirstName = "Tomohiro"
	//	player.SecondName = "Ogawa"
	//	player.Height = "176cm"
	//	player.Weight = "66kg"
	//	player.Spike = "312cm"
	//	player.Block = "290cm"
	//	player.CurrentClub = "Wolfdogs Nagoya (Japan)"
	//	player.DateOfBirth = "July 4, 1996 (age 27)"
	//	players = append(players, player)
	//
	//	player.Id = "35"
	//	player.UniformNumber = "20"
	//	player.Country = "Japan"
	//	player.Position = "L"
	//	player.FirstName = "Tomohiro"
	//	player.SecondName = "Yamamoto"
	//	player.Height = "171cm"
	//	player.Weight = "69kg"
	//	player.Spike = "301cm"
	//	player.Block = "299cm"
	//	player.CurrentClub = "Panasonic Panthers (Japan)"
	//	player.DateOfBirth = "November 5, 1994 (age 29)"
	//	players = append(players, player)
	//
	//	player.Id = "36"
	//	player.UniformNumber = "21"
	//	player.Country = "Japan"
	//	player.Position = "S"
	//	player.FirstName = "Motoki"
	//	player.SecondName = "Eiro"
	//	player.Height = "192cm"
	//	player.Weight = "80kg"
	//	player.Spike = "330cm"
	//	player.Block = "320cm"
	//	player.CurrentClub = "Wolfdogs Nagoya (Japan)"
	//	player.DateOfBirth = "June 8, 1996 (age 27)"
	//	players = append(players, player)
	//
	//	player.Id = "37"
	//	player.UniformNumber = "22"
	//	player.Country = "Japan"
	//	player.Position = "OH"
	//	player.FirstName = "Kenya"
	//	player.SecondName = "Fujinaka"
	//	player.Height = "190cm"
	//	player.Weight = "85kg"
	//	player.Spike = "340cm"
	//	player.Block = "320cm"
	//	player.CurrentClub = "Suntory Sunbirds (Japan)"
	//	player.DateOfBirth = "July 25, 1993 (age 30)"
	//	players = append(players, player)

	return players
}
